#!/bin/bash

startServer(){
    screen -d -m -S cloth java -cp MineOnline.jar gg.codie.mineonline.Server Server.jar -Xms1G -Xmx2G
}

stopServer(){
    screen -S cloth -p 0 -X stuff "stop^M"
}

messageServer(){
    screen -S cloth -p 0 -X stuff "say $@^M"
}

commandServer(){
    screen -S cloth -p 0 -X stuff "$@^M"
    sleep 0.1
    screen -S cloth -X hardcopy "last.log"
    echo `grep -a "$@" -A1 last.log | tail -n1`
}

restartServer(){
    stopServer
    sleep 10s
    startServer
}

deleteWorld(){
    stopServer
    sleep 10s
	rm -r world/
    startServer
}

wipeData(){
    rm /home/robin/minecraft/cloth/world/players/$@.dat
}

updateServer(){
    latest=$(curl -s "https://api.github.com/repos/Luminoso-256/Cloth-Server/releases/latest" | jq -r '.tag_name')
    current=$(cat CV)

	if [ ! -z "$latest" ]
		then    
			if [ "$current" != "$latest" ]
				then
					messageServer "Cloth $latest release detected, Restarting in 30 seconds and updating from $current. This may take some time, please rejoin later"
					sleep 30s
					stopServer
					sleep 10s
					echo "Detected version difference, updating Cloth version $current to $latest..."
					sleep 1s
					rm Server.jar
					wget -c "https://github.com/Luminoso-256/Cloth-Server/releases/download/$latest/Server.jar"
					chmod +x Server.jar
					echo $latest > CV
					echo "Cloth updated to version: $latest"
					startServer
				else
					echo "You already have the latest version: $current"
					messageServer "§fYou are currently on §4Dominae Cloth" 
					messageServer "§frunning §4Cloth $current"
    		fi
	fi
}

case $1 in # Check args
    "-r" | "--restart"  ) restartServer			;;
    "-u" | "--update"   ) updateServer			;;
    "-q" | "--stop"     ) stopServer			;;
    "-s" | "--start"    ) startServer			;;
    "-w" | "--wipe"     ) wipeData $2			;;
    "-a" | "--announce" ) messageServer "$2"	;;
    "-c" | "--command"  ) commandServer "$2"	;;
           "--DESTROY"  ) deleteWorld			;;
esac
