#!/bin/bash

echo "Grabbing subnet mask..."
SUBNET=$(ip r g 1 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
echo "Subnet mask found: $SUBNET"
echo "Searching network for IP adress of device matching $1... "
IP=$(nmap -sP $SUBNET >/dev/null && arp -an | grep $1 | awk '{print $2}' | sed 's/[()]//g')
echo "Local IP Address found: $IP"
echo "Starting fresh adb server"
adb kill-server
sudo adb start-server
adb connect $IP:5555
scrcpy --bit-rate 2M --max-size 800 -S